name: Auto Merge Pull Request

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행 (UTC 기준)
  workflow_dispatch:

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        run: |
          pr_list=$(gh pr list -s open --json number,createdAt | jq --arg separator ',' -r '.[] | [.number, .createdAt] | @csv' | sed 's/"//g')
          for pull_request in $pr_list; do
            pull_request_arr=(${pull_request//,/ })
            number=${pull_request_arr[0]}
            createdAt=${pull_request_arr[1]}

            now=$(date +%s)
            createdAt_iso=$(echo "$createdAt" | sed 's/Z$//' | tr 'T' ' ')
            createdAt_formatted=$(date -d "$createdAt_iso" +%FT%T%z)
            created=$(date -d "$createdAt_formatted" +%s)

            if [ $((now-created)) -ge $((2*24*60*60)) ]; then
              gh pr merge ${number%%,*} --merge
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
