name: Auto Merge Pull Request

on:
  schedule:
    - cron: '0 0,12 * * *' # 매일 아침 9시와 저녁 9
  workflow_dispatch:

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        run: |
          pr_list=$(gh pr list -s open --json number,author,createdAt | jq --arg separator ',' -r '.[] | [.number, .author.login, .createdAt] | @csv' | sed 's/"//g')
          for pull_request in $pr_list; do
            pull_request_arr=(${pull_request//,/ })
            number=${pull_request_arr[0]}
            author=${pull_request_arr[1]}
            createdAt=${pull_request_arr[2]}
            now=$(date +%s)
            createdAt_iso=$(echo "$createdAt" | sed 's/Z$//' | tr 'T' ' ')
            createdAt_formatted=$(date -d "$createdAt_iso" +%FT%T%z)
            created=$(date -d "$createdAt_formatted" +%s)
            if [ $((now-created)) -ge $((2*24*60*60)) ]; then
              if gh pr merge ${number%%,*} --merge; then
                echo "Pull request #${number%%,*} merged successfully."
              else
                gh pr comment ${number%%,*} --body "@$author 충돌이 발생해 자동으로 Merge하지 못했습니다. 수동으로 충돌을 해결한 뒤 Merge 부탁드립니다!"
              fi
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
